### ISSUE TITLE
When using Badge people see their own Picture

### ISSUE THREAD

**Issue by ZonixZA** [DOSE-420/qb-policebadge#3]
So whenever I use the badge it works perfectly with nice animations, but the picture that is shown to other players is their own picture and not my picture.

In other words i need my picture to be show on the badge when displaying to other players not their own pictures.

**Comment by DOSE-420** [comment]
Fixed in the newest update

**Comment by ZonixZA** [comment]
Tested it . 100% great work my guy much appreciated!
